//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tThuePhong
    {
        public int STT { get; set; }
        public string SoPhong { get; set; }
        public string MaKhach { get; set; }
        public System.DateTime NgayNhanPhong { get; set; }
        public System.DateTime NgayTraPhong { get; set; }
    
        public virtual tKhach tKhach { get; set; }
        public virtual tPhong tPhong { get; set; }
    }
}
