//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTrangBi
    {
        public string SoPhong { get; set; }
        public string MaThietBi { get; set; }
        public System.DateTime NgayBatDauTrangBi { get; set; }
        public System.DateTime NgayKetThucTrangBi { get; set; }
    
        public virtual tPhong tPhong { get; set; }
        public virtual tThietBi tThietBi { get; set; }
    }
}
